import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  Share,
  ActivityIndicator,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { ScreenLayout } from '../../components/ScreenLayout';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import Toast from 'react-native-toast-message';

const DocumentDraftScreen = ({ navigation, route }: any) => {
  const { document: docData, productName, complianceItem } = route.params || {};
  // ↑ alias it immediately on destructure

  const [exporting, setExporting] = useState(false);
  const [activeTab, setActiveTab] = useState<'document' | 'letter' | 'checklist'>('document');

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      const sectionsHtml = (docData.sections || []).map((s: any) => `
        <div style="margin-bottom: 24px;">
          <h3 style="font-size: 13px; font-weight: bold; color: #333; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; border-bottom: 1px solid #eee; padding-bottom: 6px;">
            ${s.title}
          </h3>
          <p style="font-size: 14px; color: #444; line-height: 1.8; white-space: pre-wrap;">${s.content}</p>
        </div>
      `).join('');

      const checklistHtml = (docData.supporting_documents_checklist || []).map((c: any) => `
        <div style="display: flex; align-items: flex-start; margin-bottom: 12px; padding: 12px; background: #f9f9f9; border-radius: 8px;">
          <div style="width: 20px; height: 20px; border: 2px solid ${c.mandatory ? '#ef4444' : '#aaa'}; border-radius: 4px; margin-right: 12px; flex-shrink: 0; margin-top: 2px;"></div>
          <div>
            <p style="font-size: 13px; font-weight: bold; color: #222; margin: 0 0 4px 0;">${c.item}</p>
            <p style="font-size: 12px; color: #666; margin: 0;">${c.description}</p>
            ${c.mandatory ? '<span style="font-size: 11px; color: #ef4444; font-weight: bold;">MANDATORY</span>' : ''}
          </div>
        </div>
      `).join('');

      const html = `
        <!DOCTYPE html><html><head><meta charset="utf-8" />
        <style>
          body { font-family: Georgia, serif; padding: 40px; color: #222; max-width: 800px; margin: 0 auto; }
          .header { border-bottom: 3px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
          h1 { font-size: 22px; color: #111; margin: 0 0 6px 0; }
          .tab-title { font-size: 18px; font-weight: bold; color: #111; margin: 30px 0 16px 0; padding-bottom: 8px; border-bottom: 2px solid #10b981; }
          .cover-letter { white-space: pre-wrap; font-size: 14px; line-height: 1.9; color: #333; background: #fafafa; padding: 24px; border-radius: 8px; border: 1px solid #eee; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #eee; font-size: 11px; color: #999; text-align: center; }
        </style>
        </head><body>
          <div class="header">
            <div style="display:inline-block;background:#f0fdf4;color:#10b981;font-size:11px;font-weight:bold;padding:4px 10px;border-radius:20px;margin-bottom:10px;">KodaTrade Document Draft</div>
            <h1>${docData.document_title}</h1>
            <div style="font-size:13px;color:#666;">Product: ${productName}${docData.agency ? ' • ' + docData.agency : ''}</div>
          </div>
          <div class="tab-title">Document Content</div>
          ${sectionsHtml}
          ${docData.cover_letter ? `<div class="tab-title">Cover Letter</div><div class="cover-letter">${docData.cover_letter}</div>` : ''}
          ${docData.supporting_documents_checklist?.length ? `<div class="tab-title">Checklist</div>${checklistHtml}` : ''}
          ${docData.important_notes ? `<div style="background:#fffbeb;border:1px solid #fcd34d;border-radius:8px;padding:16px;margin-top:24px;font-size:13px;color:#78350f;"><strong>Important:</strong> ${docData.important_notes}</div>` : ''}
          <div class="footer">Generated by KodaTrade • Draft only — review before submission • ${new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
        </body></html>
      `;

      const { uri } = await Print.printToFileAsync({ html, base64: false });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `${docData.document_title} - KodaTrade`,
        });
      }
    } catch (err: any) {
      Toast.show({ type: 'error', text1: 'Export Failed', text2: err.message });
    } finally {
      setExporting(false);
    }
  };

  // Guard — if no data came through
  if (!docData) {
    return (
      <ScreenLayout onBackPress={() => navigation.goBack()} headerTitle="Document Draft">
        <View className="flex-1 items-center justify-center">
          <Feather name="alert-circle" size={40} color="rgba(255,255,255,0.1)" />
          <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/40 text-sm mt-4">
            No document data received
          </Text>
          <TouchableOpacity onPress={() => navigation.goBack()} className="mt-6">
            <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-green-400 text-sm">
              Go back
            </Text>
          </TouchableOpacity>
        </View>
      </ScreenLayout>
    );
  }

  const TABS = [
    { id: 'document', label: 'Document', icon: 'file-text' },
    { id: 'letter', label: 'Cover Letter', icon: 'mail' },
    { id: 'checklist', label: 'Checklist', icon: 'check-square' },
  ];

  return (
    <ScreenLayout
      scrollable={false}
      onBackPress={() => navigation.goBack()}
      headerTitle="Document Draft"
      bottomAction={
        <TouchableOpacity
          onPress={handleExportPDF}
          disabled={exporting}
          className="bg-emerald rounded-2xl h-14 flex-row items-center justify-center"
          activeOpacity={0.8}
        >
          {exporting
            ? <ActivityIndicator color="black" size="small" />
            : <Feather name="download" size={18} color="black" />
          }
          <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-black text-sm ml-2 uppercase tracking-widest">
            {exporting ? 'Preparing PDF...' : 'Export as PDF'}
          </Text>
        </TouchableOpacity>
      }
    >
      {/* Header */}
      <View className="mb-5">
        <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white text-xl mb-1">
          {docData.document_title}
        </Text>
        <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/40 text-sm">
          {docData.agency}
        </Text>
        <View className="flex-row gap-3 mt-3">
          {docData.estimated_processing && (
            <View className="bg-white/5 rounded-xl px-3 py-2 flex-row items-center gap-1.5">
              <Feather name="clock" size={11} color="rgba(255,255,255,0.3)" />
              <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/50 text-xs">
                {docData.estimated_processing}
              </Text>
            </View>
          )}
          {docData.estimated_cost && (
            <View className="bg-white/5 rounded-xl px-3 py-2 flex-row items-center gap-1.5">
              <Feather name="dollar-sign" size={11} color="rgba(255,255,255,0.3)" />
              <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/50 text-xs">
                {docData.estimated_cost}
              </Text>
            </View>
          )}
        </View>
      </View>

      {/* Tabs */}
      <View className="flex-row bg-white/3 rounded-2xl p-1 mb-4">
        {TABS.map((tab) => (
          <TouchableOpacity
            key={tab.id}
            onPress={() => setActiveTab(tab.id as any)}
            className={`flex-1 flex-row items-center justify-center py-2.5 rounded-xl gap-1.5 ${activeTab === tab.id ? 'bg-white/10' : ''}`}
          >
            <Feather name={tab.icon as any} size={12} color={activeTab === tab.id ? 'white' : 'rgba(255,255,255,0.3)'} />
            <Text
              style={{ fontFamily: 'PlusJakartaSans_700Bold' }}
              className={`text-[10px] uppercase ${activeTab === tab.id ? 'text-white' : 'text-white/30'}`}
            >
              {tab.label}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Content */}
      <ScrollView showsVerticalScrollIndicator={false} className="flex-1">

        {activeTab === 'document' && (
          <View>
            {docData.purpose && (
              <View className="bg-green-500/5 border border-green-500/20 rounded-2xl p-4 mb-4">
                <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-green-300/80 text-sm leading-6">
                  {docData.purpose}
                </Text>
              </View>
            )}
            {(docData.sections || []).map((section: any, i: number) => (
              <View key={i} className="mb-5">
                <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/40 text-[9px] uppercase tracking-widest mb-2">
                  {section.title}
                </Text>
                <View className="bg-[#0d0d0d] border border-white/5 rounded-2xl p-4">
                  <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/80 text-sm leading-7">
                    {section.content}
                  </Text>
                </View>
              </View>
            ))}
            {docData.important_notes && (
              <View className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-4 mb-6">
                <View className="flex-row items-center gap-2 mb-2">
                  <Feather name="alert-triangle" size={12} color="#f59e0b" />
                  <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-amber-400 text-[9px] uppercase tracking-widest">
                    Important
                  </Text>
                </View>
                <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-amber-300/70 text-sm leading-6">
                  {docData.important_notes}
                </Text>
              </View>
            )}
          </View>
        )}

        {activeTab === 'letter' && (
          <View>
            {docData.cover_letter ? (
              <>
                <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/30 text-xs mb-3">
                  Ready-to-print. Fill in fields marked [PLACEHOLDER] with your details.
                </Text>
                <View className="bg-[#0d0d0d] border border-white/5 rounded-2xl p-5">
                  <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/80 text-sm leading-8">
                    {docData.cover_letter}
                  </Text>
                </View>
                {docData.agency_address && (
                  <View className="mt-4 bg-white/3 rounded-2xl p-4">
                    <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/30 text-[9px] uppercase tracking-widest mb-2">
                      Send To
                    </Text>
                    <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/60 text-sm leading-6">
                      {docData.agency}{'\n'}{docData.agency_address}
                    </Text>
                  </View>
                )}
              </>
            ) : (
              <View className="items-center py-12">
                <Feather name="mail" size={32} color="rgba(255,255,255,0.1)" />
                <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/30 text-sm mt-3">
                  No cover letter for this document type
                </Text>
              </View>
            )}
          </View>
        )}

        {activeTab === 'checklist' && (
          <View>
            {docData.submission_steps?.length > 0 && (
              <View className="mb-6">
                <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/40 text-[9px] uppercase tracking-widest mb-3">
                  Submission Steps
                </Text>
                {docData.submission_steps.map((step: string, i: number) => (
                  <View key={i} className="flex-row items-start mb-3">
                    <View className="w-6 h-6 rounded-full bg-emerald-500/20 items-center justify-center mr-3 mt-0.5 flex-shrink-0">
                      <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-green-400 text-[10px]">
                        {i + 1}
                      </Text>
                    </View>
                    <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/70 text-sm leading-6 flex-1">
                      {step}
                    </Text>
                  </View>
                ))}
              </View>
            )}
            {docData.supporting_documents_checklist?.length > 0 && (
              <View>
                <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white/40 text-[9px] uppercase tracking-widest mb-3">
                  Documents to Attach
                </Text>
                {docData.supporting_documents_checklist.map((doc: any, i: number) => (
                  <View key={i} className="flex-row items-start bg-[#0d0d0d] border border-white/5 rounded-2xl p-4 mb-2">
                    <View className={`w-5 h-5 rounded border-2 mr-3 mt-0.5 flex-shrink-0 ${doc.mandatory ? 'border-red-400' : 'border-white/20'}`} />
                    <View className="flex-1">
                      <View className="flex-row items-center gap-2 mb-1">
                        <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-white text-sm">
                          {doc.item}
                        </Text>
                        {doc.mandatory && (
                          <View className="bg-red-500/10 px-1.5 py-0.5 rounded">
                            <Text style={{ fontFamily: 'PlusJakartaSans_700Bold' }} className="text-red-400 text-[8px] uppercase">
                              Mandatory
                            </Text>
                          </View>
                        )}
                      </View>
                      <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/40 text-xs leading-5">
                        {doc.description}
                      </Text>
                    </View>
                  </View>
                ))}
              </View>
            )}
            <View className="mt-4 mb-8 bg-white/3 rounded-2xl p-4">
              <Text style={{ fontFamily: 'PlusJakartaSans_400Regular' }} className="text-white/30 text-xs leading-5 text-center">
                Export as PDF to use as your submission checklist.
              </Text>
            </View>
          </View>
        )}
      </ScrollView>
    </ScreenLayout>
  );
};


export default DocumentDraftScreen;